query BumpersQuery($purpose: String!, $calendarDateStart: CalendarDateTime!, $calendarDateEnd: CalendarDateTime!) {
  cms {
    bumpers (where: { purpose_contains_all: [$purpose] }) {
      items {
        ambient
        video
      }
    }

    stockMusics {
      items {
        music {
          url
        }
      }
    }
  }

  showcase {
    projects (where:{ media:VIDEOS }, take: 25) {
      name
      members {
        account {
          name
        }
      }
      media {
        stream
      }
    }
  }

  calendar {
    events(after: $calendarDateStart, before: $calendarDateEnd) {
      id
      title
      calendarName
      start
    }
  }
}
